import TipoRol from "./tipo-rol/migration";
import EstadoEmpleado from "./estado-empleado/migration";
import Usuario from "./usuario/migration";
import CategoriaStock from "./categoria-stock/migration";
import Stock from "./stock/migration";
import AbastecimientoStock from "./abastecimiento-stock/migration";
import ModificacionStock from "./modificacion-stock/migration";
import Empleado from "./empleado/migration";
import Tarea from "./tarea/migration";
import EstadoTarea from "./estado-tarea/migration";
import Cliente from "./cliente/migration";
import Pago from "./pago/migration";
import DetallePago from "./detalle-pago/migration";
import EstadoReserva from "./estado-reserva/migration";
import Reserva from "./reserva/migration";
import ReservaHabitacion from "./reserva-habitacion/migration";
import EstadoServicioSolicitado from "./estado-servicio-solicitado/migration";
import ServicioSolicitado from "./servicio-solicitado/migration";
import Servicio from "./servicio/migration";
import PromocionServicio from "./promocion-servicio/migration";
import TipoServicio from "./tipo-servicio/migration";
import ServicioHabitacion from "./servicio-habitacion/migration";
import Habitacion from "./habitacion/migration";
import TipoHabitacion from "./tipo-habitacion/migration";
import EstadoHabitacion from "./estado-habitacion/migration";
import TarifaHabitacion from "./tarifa-habitacion/migration";
import Tarifa from "./tarifa/migration";
import Ocupacion from "./ocupacion/migration";
import EstadoPDI from "./imagen-pdi/migration";
import ImagenPDI from "./estado-pdi/migration";
import { sequelize } from "./index";
// import appConfig from "../config/app";
(async () => {
  const qi = sequelize.getQueryInterface();
  // if (appConfig.nodeEnv === "development") {
  console.log("------Eliminando el SCHEMA------");
  await sequelize.query("DROP SCHEMA public CASCADE;");
  await sequelize.query("CREATE SCHEMA public;");
  // }
  console.log("------Creando Tablas------");
  console.log("------Usuario------");
  await Usuario.up(qi);
  console.log("------EstadoEmpleado------");
  await EstadoEmpleado.up(qi);
  console.log("------TipoRol------");
  await TipoRol.up(qi);
  console.log("------Empleado------");
  await Empleado.up(qi);
  console.log("------CategoriaStock------");
  await CategoriaStock.up(qi);
  console.log("------Stock------");
  await Stock.up(qi);
  console.log("------AbastecimientoStock------");
  await AbastecimientoStock.up(qi);
  console.log("------ModificacionStock------");
  await ModificacionStock.up(qi);
  console.log("------TipoServicio------");
  await TipoServicio.up(qi);
  console.log("------Servicio------");
  await Servicio.up(qi);
  console.log("------PromocionServicio------");
  await PromocionServicio.up(qi);
  console.log("------Cliente------");
  await Cliente.up(qi);
  console.log("------EstadoReserva------");
  await EstadoReserva.up(qi);
  console.log("------Reserva------");
  await Reserva.up(qi);
  console.log("------Pago------");
  await Pago.up(qi);
  console.log("------DetallePago------");
  await DetallePago.up(qi);
  console.log("------EstadoHabitacion------");
  await EstadoHabitacion.up(qi);
  console.log("------TipoHabitacion------");
  await TipoHabitacion.up(qi);
  console.log("------Habitacion------");
  await Habitacion.up(qi);
  console.log("------EstadoPDI------");
  await EstadoPDI.up(qi);
  console.log("------ImagenPDI------");
  await ImagenPDI.up(qi);
  console.log("------ReservaHabitacion------");
  await ReservaHabitacion.up(qi);
  console.log("------ServicioHabitacion------");
  await ServicioHabitacion.up(qi);
  console.log("------Tarifa------");
  await Tarifa.up(qi);
  console.log("------TarifaHabitacion------");
  await TarifaHabitacion.up(qi);
  console.log("------Ocupacion------");
  await Ocupacion.up(qi);
  console.log("------EstadoServicioSolicitado------");
  await EstadoServicioSolicitado.up(qi);
  console.log("------ServicioSolicitado------");
  await ServicioSolicitado.up(qi);
  console.log("------EstadoTarea------");
  await EstadoTarea.up(qi);
  console.log("------Tarea------");
  await Tarea.up(qi);
  console.log("------Tablas Creadas------");
  await sequelize.close();
})();
