import TipoRol from "./tipo-rol/seeder";
import EstadoEmpleado from "./estado-empleado/seeder";
import Usuario from "./usuario/seeder";
import CategoriaStock from "./categoria-stock/seeder";
import Stock from "./stock/seeder";
import AbastecimientoStock from "./abastecimiento-stock/seeder";
import ModificacionStock from "./modificacion-stock/seeder";
import Empleado from "./empleado/seeder";
import Tarea from "./tarea/seeder";
import EstadoTarea from "./estado-tarea/seeder";
import Cliente from "./cliente/seeder";
import Pago from "./pago/seeder";
import DetallePago from "./detalle-pago/seeder";
import EstadoReserva from "./estado-reserva/seeder";
import Reserva from "./reserva/seeder";
import ReservaHabitacion from "./reserva-habitacion/seeder";
import { sequelize } from "./index";
(async () => {
  const qi = sequelize.getQueryInterface();
  console.log("------Llenando datos------");
  console.log("------TipoRol------");
  await TipoRol.seed(qi);
  console.log("------EstadoEmpleado------");
  await EstadoEmpleado.seed(qi);
  console.log("------Usuario------");
  await Usuario.seed(qi);
  console.log("------CategoriaStock------");
  await CategoriaStock.seed(qi);
  console.log("------Stock------");
  await Stock.seed(qi);
  console.log("------AbastecimientoStock------");
  await AbastecimientoStock.seed(qi);
  console.log("------ModificacionStock------");
  await ModificacionStock.seed(qi);
  console.log("------Empleado------");
  await Empleado.seed(qi);
  console.log("------Tarea------");
  await Tarea.seed(qi);
  console.log("------EstadoTarea------");
  await EstadoTarea.seed(qi);
  console.log("------Cliente------");
  await Cliente.seed(qi);
  console.log("------Pago------");
  await Pago.seed(qi);
  console.log("------DetallePago------");
  await DetallePago.seed(qi);
  console.log("------EstadoReserva------");
  await EstadoReserva.seed(qi);
  console.log("------Reserva------");
  await Reserva.seed(qi);
  console.log("------ReservaHabitacion------");
  await ReservaHabitacion.seed(qi);
  console.log("------Tablas llenadas------");
})();
