import TipoRol from "./tipo-rol/seeder";
import EstadoEmpleado from "./estado-empleado/seeder";
import Usuario from "./usuario/seeder";
import CategoriaStock from "./categoria-stock/seeder";
import Stock from "./stock/seeder";
import AbastecimientoStock from "./abastecimiento-stock/seeder";
import ModificacionStock from "./modificacion-stock/seeder";
import { sequelize } from "./index";
(async () => {
  const qi = sequelize.getQueryInterface();
  console.log("------Llenando datos------");
  console.log("------TipoRol------");
  await TipoRol.seed(qi);
  console.log("------EstadoEmpleado------");
  await EstadoEmpleado.seed(qi);
  console.log("------Usuario------");
  await Usuario.seed(qi);
  console.log("------CategoriaStock------");
  await CategoriaStock.seed(qi);
  console.log("------Stock------");
  await Stock.seed(qi);
  console.log("------AbastecimientoStock------");
  await AbastecimientoStock.seed(qi);
  console.log("------ModificacionStock------");
  await ModificacionStock.seed(qi);
  console.log("------Tablas llenadas------");
})();
